### ISSUE TITLE
Error,,, In build.gradle,, It connecting to some stuffs (resolved)

### ISSUE THREAD

**Issue by pig533** [NathanW-05/AutoDupe#1]
Hey, I have Looked at yourt  Buidl.gradle files and it looks like it is getting Files from A fake, spongebobered prespotiry. also yuor code sucx Lol

**Comment by NathanW-05** [comment]
shut up retard.

**Comment by pig533** [comment]
bro ur packet events arent even getting fired nice rat Kid Lel

**Comment by NathanW-05** [comment]
Yeah they do, they get fired when you send a packet, duh?
